import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useForm } from "react-hook-form";
import { useRouter } from 'next/router';
import { CreateGraphQLClient } from '../graphql';

function Home() {
  const router = useRouter();
  const { 
    register, 
    handleSubmit,
    formState: { errors } 
  } = useForm();

  const onSubmit = (data: {tokenRequired: string}) => {
    CreateGraphQLClient(data.tokenRequired);
    router.push('/repositories');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Mini Git Test Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-wrap">
        <div className="w-full max-w-xs">
          <form className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" onSubmit={handleSubmit(onSubmit)}>
            <div className="mb-4">
              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="token">
                Github API token. Please enter a valid one, because it's no validation in here.
              </label>
              <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="token" {...register("tokenRequired", { required: true })} />
              {errors.tokenRequired && <span className="text-red-500 text-xs italic">This field is required</span>}
            </div>      
            <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">Sing In</button>
          </form>
        </div>
      </main>
    </div>
  );
};

export default Home;